mysqldata:
    image: learninglayers/mysql-data
    env_file:
        - common.env
        - mysql/mysql.env
mysql:
    build: mysql
    env_file:
        - common.env
        - mysql/mysql.env
    volumes_from:
        - mysqldata
    # volumes:
    #     - mysql/:/var/lib/mysql/
    ports:
        - "127.0.0.1:3307:3306"
mysqlcreate:
    build: mysql-create
    links:
        - mysql
    env_file:
        - common.env
        - mysql/mysql.env
        - secret.env
    volumes:
        - sqlfile/:/sqlfile/
adapterdata:
    build: adapter-data
    env_file:
        - common.env
adapterservices:
    build: adapter-externals
    volumes_from:
        - surveysnginx
        - qvsnginx
        - oidcnginx
        - tethysuserstoragenginx
        - openldapaccountnginx
        # - swiftnginx
adapter:
    image: learninglayers/adapter
    volumes_from:
        - adapterdata
        - qvsfrontend
        - surveysfrontend
        - adapterservices
    volumes:
        - ssl/:/usr/local/openresty/conf/ssl/
    env_file:
        - common.env
    ports:
        - "127.0.0.1:8383:443"
    links:
        - qvs
        - surveys
        - oidc
        - openldapaccount
        # - swift
qvsdata:
    build: mobsos-query-visualization-data
    env_file:
        - common.env
        - mobsos-query-visualization/QVS.env
qvsfrontend:
    build: mobsos-query-visualization-frontend
    env_file:
        - common.env
        - mobsos-query-visualization/QVS.env
qvs:
    build: mobsos-query-visualization
    env_file:
        - common.env
        - mobsos-query-visualization/QVS.env
    volumes_from:
        - qvsdata
    volumes:
        - /dev/urandom:/dev/random
    links:
        - mysql
qvsnginx:
    build: mobsos-query-visualization-nginx
openldapdata:
    image: learninglayers/openldap-data
    env_file:
        - openldap/LDAP.env
openldap:
    build: openldap
    env_file:
        - openldap/LDAP.env
    ports:
        - "127.0.0.1:389:389"
    volumes_from:
        - openldapdata
    volumes:
        - /dev/urandom:/dev/random
openldapaccountdata:
    image: learninglayers/openldapaccount-data
openldapaccount:
    image: learninglayers/openldapaccount
    volumes_from:
        - openldapaccountdata
    ports:
        - "127.0.0.1:8083:8080"
    links:
        - openldap
        - tethysuserstorage
    environment:
        - TETHYS_IP=tethysuserstorage
        - PWM_LDAP_ADMINS=<value>koren</value><value>nicolaescu</value>
    env_file:
        - common.env
        - openldap/LDAP.env
    links:
        - openldap
    volumes:
        - /dev/urandom:/dev/random
openldapaccountnginx:
    build: openldapaccount-nginx
oidcdata:
    build: openidconnect-data
    env_file:
        - common.env
        - openidconnect/OIDC.env
        - openldap/LDAP.env
oidc:
    build: openidconnect
    env_file:
        - common.env
        - openidconnect/OIDC.env
        - openldap/LDAP.env
    volumes_from:
        - oidcdata
    links:
        - mysql
        - openldap
    ports:
        - "127.0.0.1:8080:8080"
    volumes:
        - /dev/urandom:/dev/random
oidcnginx:
    build: openidconnect-nginx
surveysdata:
    build: mobsos-surveys-data
    env_file:
        - common.env
        - mobsos-surveys/SURVEYS.env
surveys:
    build: mobsos-surveys
    env_file:
        - common.env
        - mobsos-surveys/SURVEYS.env
    links:
        - mysql
    volumes_from:
        - surveysdata
    volumes:
        - /dev/urandom:/dev/random
surveysfrontend:
    build: mobsos-surveys-frontend
    env_file:
        - common.env
        - mobsos-surveys/SURVEYS.env
surveysnginx:
    build: mobsos-surveys-nginx
# swift:
#     image: learninglayers/swift
#     ports:
#         - "127.0.0.1:8082:8080"
#     env_file:
#         - common.env
#         - swift/SWIFT.env
swiftnginx:
    build: swift-nginx
tethysuserstorage:
    image: learninglayers/tethys-userstorage
    ports:
        - "127.0.0.1:8081:8080"
    env_file:
        - common.env
        - swift/SWIFT.env
        - tethys-userstorage/TETHYS.env
    volumes:
        - /dev/urandom:/dev/random
tethysuserstoragenginx:
    build: tethys-userstorage-nginx
mobsosmonitordata:
    build: ./mobsos-monitor-data
    env_file:
        - common.env
        - mobsos-monitor/MM.env
        - openidconnect/OIDC.env
mobsosmonitor:
    build: ./mobsos-monitor
    env_file:
        - common.env
        - mobsos-monitor/MM.env
        - mysql/mysql.env
    links:
        - mysql
    volumes_from:
        - mobsosmonitordata
        - adapterdata
